- modules/azure/vnet/lb-ingress.tf
In Azure we need to have explicit *.g8s for
services like happa, api, etc. to work.
We don't use ingress dns at all, so just remove it.
This is not required in AWS.
> Add *.g8s wildcard

- cloud-config/master.yaml.tmpl
Switch default storage class to managed disks.
By default Azure creates blob and tries to attach it to instance, this works only for VMs with unmanaged disks (Old-style), we use managed disks VMs.
> Use managed disks as default storage class

- modules/container-linux/main.tf
- modules/container-linux/outputs.tf
- modules/container-linux/variables.tf
- platforms/azure/giantnetes/main.tf
Terraform 0.11.1 reserves "version" parameter.
This change renames version to coreos_version.
> Avoid using version param in container linux module

- cloud-config/master.yaml.tmpl
https://github.com/giantswarm/giantswarm/issues/2347
- store 30 rotated files instead of 10 (estimates size ~3G)
- add flag necessary to continue using legacy audit log in 1.8 [1]
1 - https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#legacy-audit
> Increase audit log size

- cloud-config/master.yaml.tmpl
In azure we can not use load balancer if it points to the same node.
> Fix etcd defragmentation service. Use 127.0.0.1 for etcd

- cloud-config/master.yaml.tmpl
As we are using calico with kubernetes datastore, `calico-node` cluster role requires different rules from those we are using with etcd backed calico. Rules are taken from upstream: https://github.com/projectcalico/calico/blob/master/v3.0/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
Also this PR removes calico policy-controller related RBAC stuff
> Calico fix RBAC rules

- examples/aws/example-build/backend.tf
- examples/aws/example-build/profile.tf
- platforms/aws/giantnetes/provider.tf
this allows to use AWS profiles. Including case with assume role.
Only limitation kind of we need to agree that we will define profiles with codename of the clusters. Not with the name of the customer as we are doing at the moment.
> Add support for aws profiles

- platforms/azure/giantnetes/variables.tf
We need thick worker VMs in Azure in order to host ELK stack. Standard_DS3_v2 is similar to m4.xlarge in aws.
> Change default worker size in Azure

- modules/aws/vpc/vpc.tf
aws-operator already has dependency on specific name format.
> Use old route table names for private route tables.

- modules/azure/vault/vault.tf
- modules/azure/worker-as/worker-as.tf
Right now `terraform apply` detects Kubernetes managed volumes as a change. Also make sure we are not recreating Vault if new CoreOS version was released.
> Ignore terraform changes for Vault and kubernetes PVs

- modules/aws/master/master.tf
- modules/aws/worker-asg/worker-asg.tf
In calico slack they recommended to use protocol 4 instead of 94 in security groups.
Unfortunately i can not confirm that it fixes the IPIP tunnels problem, but at least this does not break anything. All last roll outs done with this change.
> Use protocol 4 for IPIP

- modules/aws/bastion/bastion.tf
- modules/aws/dns/dns.tf
- modules/aws/master/master-elb.tf
- modules/aws/master/master.tf
- modules/aws/s3/s3.tf
- modules/aws/vault/vault-elb.tf
- modules/aws/vault/vault.tf
- modules/aws/vpc/vpc-subnet-bastion.tf
- modules/aws/vpc/vpc-subnet-elb.tf
- modules/aws/vpc/vpc-subnet-vault.tf
- modules/aws/vpc/vpc-subnet-worker.tf
- modules/aws/vpc/vpc.tf
- modules/aws/vpn/vpn.tf
- modules/aws/worker-asg/worker-asg.tf
- modules/aws/worker-asg/worker-elb.tf
- platforms/aws/giantnetes/main.tf
New tags:
- giantswarm.io/installation=CLUSTER_NAME
- kubernetes.io/cluster/CLUSTER_NAME=owned
Instead of:
- Environment=CLUSTER_NAME
- KubernetesCluster=CLUSTER_NAME
Terraform does not support interpolation for tag name that's why such ugly constructions are used. See bug https://github.com/hashicorp/terraform/issues/14516
> Use new tagging for AWS

- cloud-config/master.yaml.tmpl
- cloud-config/worker.yaml.tmpl
- ignition/aws/master.yaml.tmpl
- ignition/aws/worker.yaml.tmpl
New docker does not have this flag and legacy registry support.
This change is compatible with prev docker version.
Also update `shared` to `rshared`, because new docker forces it.
```
must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/", propagation: "shared".
```
From [official documentation](https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation) `rshared` is 
```
The same as shared, but the propagation also extends to and from mount points nested within any of the original or replica mount points.
```
> Remove docker flag disable legacy registy

- modules/aws/vpc/vpc.tf
We had etcd-backup jobs failing, because of too strict S3 endpoint policy.
> Allow etcd-backup bucket in vpc endpoint

- cloud-config/master.yaml.tmpl
We manage this service by timer, so we don't want it to be started on boot. Starting it on boot causes race conditions sometimes, because systemd will start etcd3-defragmentation immediately after etcd3, so etcd3 was not be able to start.
ignition already has this service disabled.
> Disable etcd3-defragmentation service

- cloud-config/master.yaml.tmpl
- cloud-config/worker.yaml.tmpl
due to cloud-config specifics we need to stop service also, because cloud-config applied later and service already was started.
> Properly disable wait online service

- .circleci/config.yml
- misc/e2e-aws.sh
- platforms/aws/giantnetes/main.tf
- added script `e2e-aws.sh`
- added CircleCI jobs `e2eTestAWS` that requires approve
Right now script will provision whole cluster, will check that all nodes are in `Ready` state and desctroy cluster afterwards.
TODO (for next PR): add actual k8s e2e conformance testing.
> Add e2e CI script for AWS

- ignition/aws/master.yaml.tmpl
- ignition/aws/worker.yaml.tmpl
- misc/e2e-aws.sh
- modules/aws/bastion/bastion-iam.tf
- modules/aws/bastion/bastion.tf
- modules/aws/bastion/variables.tf
- modules/aws/master/master-elb.tf
- modules/aws/master/master-iam.tf
- modules/aws/master/master.tf
- modules/aws/master/variables.tf
- modules/aws/vault/variables.tf
- modules/aws/vault/vault-elb.tf
- modules/aws/vault/vault.tf
- modules/aws/vpc/variables.tf
- modules/aws/vpc/vpc.tf
- modules/aws/worker-asg/variables.tf
- modules/aws/worker-asg/worker-asg.tf
- modules/aws/worker-asg/worker-elb.tf
- modules/aws/worker-asg/worker-iam.tf
- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
List of changes:
- configurable route53 records
- configurable tags for s3 buckets
- configurable IAM region (as China uses `-cn` prefix)
- configurable pod-infra-container-image
> Changes, required for China region

- modules/azure/blob/blob.tf
This change improves security for ignition container in Azure Blob storage. Unfortunately i did not find elegant solutions to completely prevent anonymous access (and still be able to use from VM).
This change disallows blobs listing in container: `curl 'https://containerxxx.blob.core.windows.net/ignition?restype=container&comp=list'`.
Related to: https://github.com/giantswarm/giantswarm/issues/3041
~I'll also play with [SAS](https://www.terraform.io/docs/providers/azurerm/d/storage_account_sas.html) (temporary access URL). So this PR can be updated.~
> Improve ignition container security

- modules/azure/blob/blob.tf
- modules/azure/master-as/master-as.tf
- modules/azure/master-as/master-ignition.tf
- modules/azure/master-as/variables.tf
- platforms/azure/giantnetes/main.tf
This change makes ignition container private and creates temporary SAS credentials for 3 months. SAS is data source and it's renewed everytime terraform run. Also use md5 sum for ignition object name, this allows to prevent master recreation if no changes in ignition data. 
Fixes: https://github.com/giantswarm/giantswarm/issues/3041
> Use SAS for ignition object access.

- modules/aws/vault/variables.tf
- modules/aws/vault/vault.tf
- modules/azure/vnet/nsg-vault.tf
- platforms/aws/giantnetes/main.tf
This is needed in order to get vault machine monitored in cloud,
prometheus needs to be allowed to scrape vault machine node-exporter.
> Allow workers to access vault node exporter

- ignition/aws/master.yaml.tmpl
- ignition/aws/worker.yaml.tmpl
- ignition/azure/master.yaml.tmpl
- ignition/azure/worker.yaml.tmpl
in Atlantis and axolotl the pull of images is quite slow and killing kubelet in the process is slowing the pull even more
We did similar fix also for guest cluster
> increase-kubelet-start-timeout

- ignition/aws/master.yaml.tmpl
- ignition/azure/master.yaml.tmpl
By default controller starts worker number equal to number of cores. Every worker consumes 45MB memory in stand-by, this causes OOM kills (for default limit 700MB) if core number >=16 (Big VMs).
Fixes https://github.com/giantswarm/giantswarm/issues/3536
> Use static worker count for nginx

- modules/aws/master/master.tf
- modules/aws/master/variables.tf
- platforms/aws/giantnetes/main.tf
It was not propagated into master module. Default were working fine, but when we set another value we found that it's broken.
> Fix etcd_dns entry propagation

- ignition/aws/master.yaml.tmpl
- ignition/azure/master.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/3717
I have tested this version in AWS and Azure host clusters. Even [release page describes](https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.16.2) a breaking change it does not affect since we don't apply any psp to IC in host clusters. Adding the security context at container level in our case make the deployment fails (because cannot validate against any PSP)
> Upgrade nginx version to 0.16.2

- docs/installation-guide-aws.md
- docs/installation-guide-azure.md
- examples/aws/example-build/bastion-users.yaml
- examples/aws/example-build/users.yaml
- examples/azure/example-build/bastion-users.yaml
- examples/azure/example-build/users.yaml
- ignition/bastion-users.yaml
- ignition/users.yaml
- misc/e2e-aws.sh
- misc/e2e-azure.sh
Refactoring. Move ssh users, which is cluster secific and in general configuration into "build" directory. Use symlinks to build directory.
> Move ssh users into build

- modules/aws/vpc/outputs.tf
- modules/aws/vpc/variables.tf
- modules/aws/vpc/vpc-subnet-bastion.tf
- modules/aws/vpc/vpc.tf
- modules/aws/vpn/vpn.tf
- platforms/aws/giantnetes/main.tf
As part of enabling logs on bastions, internet access should be turned on there. Also, as bastions don't have now public addresses, they can be associated with private routing table.
- switch nat gateways to elb subnets (which are the only in public now)
- move IPSec routes from public routing table into private, which is
now used by bastions
> Associate bastions into private routing table

- misc/e2e-aws.sh
- misc/e2e-azure.sh
We need well-recognized names for e2e tests for ci-cleaner. So use `e2e-terraform-<commit hash 6 chars>` and w/o dashes for Azure, because name restrictions for Azure storage accounts.
From [Azure docs](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-storage-account-name-errors)
> Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.
> Use e2e-terraform-XXXXXX for CI (w/o dashes for Azure)

- modules/aws/worker-asg/worker-asg.tf
Part of: https://github.com/giantswarm/giantswarm/issues/4168
Align with approach we use in aws-operator. So while upgrade we scale up on 1 VM and then start rolling others.
Tested in `ginger`
> Improve AWS ASG scaling settings

- templates/master.yaml.tmpl
- templates/worker.yaml.tmpl
Part of: https://github.com/giantswarm/giantswarm/issues/4173
This is only step 1 into migrating to proper calico certificates. This change makes sure we have `/etc/kubernetes/ssl/calico/` with `etcd-ca` `etcd-cert` `etcd-key`. At the moment we use ones from `/etc/kubernetes/ssl/etcd` and they passed (to CNI) via [environment variables](https://github.com/giantswarm/giantnetes-terraform/blob/master/templates/master.yaml.tmpl#L2852-L2854) in k8s-kubelet.service, which is not right.
> Create proper calico certificates

- templates/master.yaml.tmpl
- templates/worker.yaml.tmpl
Kubernetes v1.11.1 (and also .2 and .3) apiserver has a memory leak.
There is a fix in apimachinery for it, but upstream release PR is
waiting for testing atm. To mitigate this issue for us in the meanwhile,
we built our own patched version of hyperkube image to enable k8s
v1.11.x clusters.
Towards https://github.com/giantswarm/giantswarm/issues/4187
> Use patched k8s v1.11.1 hyperkube image

- templates/master.yaml.tmpl
Fixes: https://github.com/giantswarm/giantswarm/issues/4159
- Set calico limits (calico-node - 0.25 cpu, 150mb, calico-kube-controllers - 0.25 cpu, 100mb - based on metrics)
- Bugfix release update to 3.2.2
- Switch to proper certificates (they now in place)
- Remove workaround that was done for calico upgrade from 3.0 to 3.2
> Multiple calico improvements

- templates/master.yaml.tmpl
calico-kube-controller is unable to start with kube-proxies in ipvs mode (the reason can be different, but that is just the non-working configuration which breaks stuff). also after calico-kube-controller is up and running, switching back to the ipvs doesn't break stuff. So that's only kube-controller booting issue
Requires more investigation
> Switch back to iptables in kube-proxy

- templates/master.yaml.tmpl
please see my comment here https://github.com/giantswarm/giantnetes-terraform/pull/161
We have separate Calico manifests for aws and azure and each should contain serviceaccount. Why? because this makes easier to maintain calico manifests as they are 99% similar to upstream ones.
> Remove calico-node service account properly

- templates/master.yaml.tmpl
I didn't find issues I had before. Rolled this out to gauss/gollum - also didn't get any issues
> Enable ipvs in kube-proxy

- templates/master.yaml.tmpl
part of: https://github.com/giantswarm/giantswarm/issues/4159
I got answers in calico slack:
- install-cni also monitors etcd certificates for changes (so we can not move to initContainer)
- for k8s datastore, it was moved to initContainer upstream [two weeks ago](https://github.com/projectcalico/calico/commit/b146897bd11781b55c7bb2666a4ee1d481b4e23c), so do the same.
> Resource limits for install-cni

- templates/master.yaml.tmpl
related: https://github.com/giantswarm/giantswarm/issues/4662
> Add coredns autopath feature

- misc/e2e-aws.sh
- misc/e2e-azure.sh
- modules/aws/master/master.tf
- modules/aws/master/variables.tf
- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
- templates/master.yaml.tmpl
- templates/worker.yaml.tmpl
Requires CoreOS 1995.0.0.
Tested in gauss and ghost.
depens on: https://github.com/giantswarm/installations/pull/602
We can not use predictable disk names with ignition
as https://github.com/coreos/bugs/issues/2481 was fixed.
> Use persistent paths for disks

- modules/azure/vault/vault.tf
Vault was redeployed, when we switched to alpha channel. Tested locally and filter was an issue. Seems we just copy-paste it from AWS.
> Fix issue with redeployin Vault in Azure

- templates/master.yaml.tmpl
- templates/worker.yaml.tmpl
- k8s 1.13.1
- etcd 3.3.10
- calico 3.4.0
- coredns 1.3.0
Tested in `gauss` and `ghost`
Related: https://github.com/giantswarm/giantswarm/issues/4540 https://github.com/giantswarm/giantswarm/issues/4579
> Update k8s, etcd, calico, coredns

- templates/master.yaml.tmpl
- templates/worker.yaml.tmpl
Running kubelet as a container does not expose the `dockershim` socket to the host automatically. By exposing it we can access the common kubernetes CR-I and have enormous benefits in debugging our applications remotely running in the control plane. 
For instance a series of tools out there like https://github.com/solo-io/kubesquash use the common CR interface to operate against the docker API.
Doing that we can also build tools that can operate remotely.
> Mount locally dockershim

- modules/aws/s3/s3.tf
- modules/aws/worker-asg/worker-iam.tf
add perm for forwarding logs to cloudwatch to worker IAM
I think it makes sense to have this by default
towards https://github.com/giantswarm/giantswarm/issues/4830
> add-worker-permissions-for-cloudwatch-logs

- templates/master.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/5216
I don't want to use containers for those debug tools as that adds an additional point of failure in the debug process. But that's just me. Do you think we need containers for those utils?
> Add calicoctl/etcdctl/crictl tools for master

- platforms/aws/giantnetes/main.tf
- platforms/azure/giantnetes/main.tf
without the backend definition terraform does not know which backend type use
> define-backend-type

- templates/master.yaml.tmpl
Align with tenant clusters so we can add priority class `giantswarm-critical` for CP components (we can't reuse system priorityclasses as those works only for `kube-system` ns)
> Add giantswarm-critical priority class

- misc/e2e-aws.sh
- misc/e2e-azure.sh
- platforms/aws/giantnetes/main.tf
- platforms/azure/giantnetes/main.tf
This solves a bug encountered by @corest during e2e tests. Those are the unique cases where we run Terraform with a local backend so we must disable the configuration of the backends
> Fix terraform init

- modules/azure/vnet/vnet-subnets.tf
looks like we still need to use the deprecated method of network security group association and route table association   until azureRM reaches 2.0
at least we are prepared and  afterward, we just remove the 3 lines
see this https://github.com/hashicorp/terraform/issues/19722
> fix-azure-subnet-nsg-association

- modules/aws/worker-asg/worker-iam.tf
Current setup never gives access for fluentd to Cloudwatch with error
```
fluentd-686d7dfcf9-xbvkx fluentd 2019-03-26 13:28:58 +0000 [warn]: #0 failed to flush the buffer. retry_time=10 next_retry_seconds=2019-03-26 13:28:58 +0000 chunk="584ff0ccf66a339bbc2cf6b768090049" error_class=Aws::CloudWatchLogs::Errors::AccessDeniedException error="User: arn:aws:sts::452825986764:assumed-role/viking-worker/i-0e5cb8fbb70ee8d6b is not authorized to perform: logs:DescribeLogGroups on resource: arn:aws:logs:eu-central-1:452825986764:log-group::log-stream:"
```
This is because of wrong iam role access.
> Fix worker iam-role access to logs

- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
- platforms/azure/giantnetes/main.tf
- platforms/azure/giantnetes/variables.tf
- templates/master.yaml.tmpl
In order to use Jumbo frames we want to make MTU configurable as a parameter that can be modified by each installation.
Towards: https://github.com/giantswarm/giantswarm/issues/2117
https://docs.projectcalico.org/v3.5/usage/configuration/mtu
> Add configurable mtu for Calico

- modules/aws/vault/vault-iam.tf
- modules/aws/vault/vault-kms-endpoint.tf
- modules/aws/vault/vault-kms.tf
- modules/aws/vault/vault.tf
During the provision of `giraffe` kms endpoint and other stuff were created but in AWS China is not possible so we have to flag the creation
Tested in giraffe
> Disable kms auto-unseal aws

- README.md
It seems the repo for `terraform-provider-ct` has [been renamed ](https://github.com/poseidon/terraform-provider-ct/commit/77d8a2d41066aa40497f1fdf8a1e37a3f71311ac) which breaks pulling down the module (at least it did for me).
> ct provider URL needs updating

- templates/bastion.yaml.tmpl
- templates/master.yaml.tmpl
- templates/vault.yaml.tmpl
- templates/vpn.yaml.tmpl
- templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/6070
I've disabled TCP Forwarding and Agent Forward only in the case of the workers because we don't jump on TC via workers
This one 
> protection for buffer overflows needs to be active, which seems to be standard. In Linux the file /etc/sysctl.conf should have kernel.exec-shield = 1 and kernel.randomize_va_space = 2. The NX-Bit styrting with Linux-Kernel 2.6.8 needs to be enabled by default
is already satisfied in the OS as below showed
```
WARNING: CONTROL-PLANE NODE | giantswarm@master-172-16-227-131 ~ $ grep -Fw nx /proc/cpuinfo
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable …
```
> CP components ssh config and hardening

- platforms/aws/giantnetes/variables.tf
Add  variable type to AWS vault subnet
to fix
```
module.master.aws_volume_attachment.master_etcd[2]: Refreshing state... [id=vai-3116947638]
Error: Invalid value for module argument
on main.tf line 58, in module "vpc":
58:   subnets_vault      = "${var.subnets_vault}"
The given value is not suitable for child module variable "subnets_vault"
defined at ../../../modules/aws/vpc/variables.tf:26,1-25: list of any single
type required.
Releasing state lock. This may take a few moments...
```
> Add  variable type to aws vault subnet

- templates/master.yaml.tmpl
Towads https://github.com/giantswarm/giantswarm/issues/6467
This role allows 
- `list` everything
- `get` everything except draughtsman cm and all secrets
> Extend readonly role

- templates/files/k8s-resource/rbac-roles.yaml
clusterroles are not namespaced, it works, but it ends up without a namespace which could cause confusion and maybe at some point even a break if upstream decides to be stricter in validating on resources
> remove ns from clusterrole

- misc/e2e-aws.sh
When running the e2e tests on AWS, if the terraform destroy step fails the test is considered red, without considering the actual test (= kubernetes nodes status) result.
This leads to a high number of false negatives.
IMHO we should ignore any failure in the teardown process and just consider a test successful if the desired nodes are `Running`.
The leftovers on the cloud provider will be removed by the CI cleaner.
> ignore errors in the teardown phase

- modules/azure/dns/dns.tf
Fixed a bug in the terraform module "dns".
See comments in the code.
> Always deploy the delegated DNS zone in terraform

- modules/aws/vpc/vpc.tf
This PR https://github.com/giantswarm/aws-operator/pull/2062/files introduced lookup for a control-plane VPC, which works only when there are separate accounts used for control-plane and tenant in aws. In China we have a single account, so filter from here https://github.com/giantswarm/aws-operator/blob/master/service/controller/resource/cpvpc/resource.go#L100-L127 returns multiple records. 
With additional tag it will be easier to get control-plane vpc id
> Add cluster-type tag

- platforms/aws/giantnetes/variables.tf
towards PM https://github.com/giantswarm/giantswarm/issues/7729
we had some issues on gridscale jumphost when they were super small as the ssh  service got killed. so let's try to use t3 instances and add some extra resources
next step would be adding node-exporter service on bastions
> jumphost-instance-sizing

- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
- platforms/azure/giantnetes/main.tf
- platforms/azure/giantnetes/variables.tf
- templates/files/manifests/api-server.yaml
Enabled by default doesn't cause any issues, but drops unwanted error messages in logs.
> Make OIDC disabled by default

- docs/installation-guide-aws.md
As with future internal networking introduction (basically duplicating all the ELBs with internal), we will need more addresses. I did this change already for `asgard` as well as for the new installation I'm working on now. So this just about aligning docs
> Inrease elb subnet sizes for future networking changes

- templates/files/k8s-resource/calico-all.yaml
- templates/files/k8s-resource/default-backend-dep.yaml
- templates/files/k8s-resource/ingress-controller-dep.yaml
This was missed during the update to k8s 1.16 as those resources were already there.
P.S. @calvix maybe worth to check hive repo as well as you would get into same issue there with new installation
> Fix deployment specs for new k8s

- templates/files/k8s-resource/calico-all.yaml
calico is acting weird on nodes with 2 interfaces from the same network, ignoring eth1 is fixing the issue
> fix-asg-calico

- misc/e2e-azure.sh
Towards: https://github.com/giantswarm/giantswarm/issues/7981
This PR cleans up the NS delegation record from azure.gigantic.io after e2e tests finish.
> Cleanup NS record after e2e

- templates/files/config/kubelet-master.yaml.tmpl
- templates/files/config/kubelet-worker.yaml.tmpl
enable parallel pulls and add some config values
this helped axolotl and giraffe start much faster even with some bad quay images ( legacy aws-operator)
basically slow quay pull won't slow other images
should be probably imported also to TC
> improve-image-pulling-in-china

- modules/azure/blob/blob.tf
Towards https://github.com/giantswarm/giantswarm/issues/8949
I tested forcing https in the storage account on azure on impala.
It works just fine, so I edited the terraform module in order to force https and address the security hint from azure advisor.
> Force https for storage account

- templates/files/conf/k8s-addons
- templates/files/k8s-resource/ingress-controller-daemonset.yaml
- templates/files/k8s-resource/ingress-controller-svc.yaml
The starting point of this funny bug is this PM: https://github.com/giantswarm/giantswarm/issues/9775
The initial symptom: nginx ingress controller not reachable in the control plane when the pods were all scheduled in the master nodes and none in the worker nodes.
The problem is that we use `externalTrafficPolicy: Local` which causes `kube-proxy` to avoid doing NAT on incoming requests. Those requests will fail if the POD is not running in the node where the request is arrived and this ultimately makes the azure load balancer think the node is unhealthy.
Not sure if AWS control planes work and how they do that.
k8s sig network people tells this is intended behaviour, so we have no choice but switch to `externalTrafficPolicy: Cluster` https://github.com/kubernetes/kubernetes/issues/89831
> Switched to externalTrafficPolicy Cluster 

- modules/aws/s3/s3.tf
- modules/aws/s3/variables.tf
- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
fixing the aftermatch after his PR https://github.com/giantswarm/giantnetes-terraform/pull/318
caused that ginger access logs s3 bucket was deleted but due to life-cycle policy to 365 days the logs will be available and s3 bucket name is not available to use
so adding an optional prefix to fix possible name conflicts and have ginger back to working state
ginger will have this in the bootstrap:
```
export TF_VAR_s3_bucket_prefix="giantswarm-"
```
> 'add-optional-s3bucket-prefix'

- modules/flatcar-linux/data/version.sh
- modules/flatcar-linux/main.tf
- modules/flatcar-linux/outputs.tf
- modules/flatcar-linux/variables.tf
- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
This PR introduces to the GS CP Flatcar.
I've opted for the current approach. If it is not set it up explicitly `flatcar_linux_version`, CoreOS is still used as OS for all CP compoments.
This covers only AWS. For Azure we need to refactor even more, because unfortunately the abstraction is not so powerful. Azure modules indeed explicitly define as publisher `CoreOS`. oh well let's leave this discussion for a different PR.
I've already executed `terraform plan` and it works. Need to run `apply` to create `galileo` as first CP with Flatcar Linux.
> [aws] Flatcar Linux (no China)

- platforms/aws/giantnetes/variables.tf
I've deployed Flatcar in China installations already. 
Also CoreOS eol has come. 
So let's move further
> Make flatcar default for AWS installations

- modules/azure/vnet/vnet-subnets.tf
towards: https://github.com/giantswarm/giantswarm/issues/11499
we need to add the Microsoft.Storage `service endpoint` to the workers subnet to be able to allow the control plane to access storage accounts in the TC's resource groups
> Add Microsoft.Storage service endpoint to worker subnet

- templates/files/conf/setup-kubelet-environment
This is to avoid the situation where values are appended again after
reboot.
> setup-kubelet-environment: remove env file before writing

- misc/e2e-aws.sh
- misc/e2e-azure.sh
- templates/files/k8s-resource/aws-cni.yaml
this can help when the cluster is auto-scaling a lot to speed up process but the problem is that it will waste IPs on  each node so big number can lead to unused assigned IP and in small subnets lead to exhaustion of subnets
> reduce-aws-cni-warm-ip

- templates/master.yaml.tmpl
- templates/worker.yaml.tmpl
There are situations where K8s API is not available when the node
starts. E.g. setting up a fresh cluster.
This now will only try to remove the node to mitigate the original
issue.
See https://github.com/giantswarm/giantnetes-terraform/pull/338#issuecomment-652511824
> templates: make k8s-setup-delete-old-node work by best effort

- modules/aws/bastion/bastion-logs.tf
- modules/aws/bastion/bastion.tf
- modules/aws/dns/dns.tf
- modules/aws/master/master.tf
- modules/aws/s3/s3.tf
- modules/aws/vault/vault-elb.tf
- modules/aws/vault/vault.tf
- modules/aws/vpc/vpc.tf
- modules/aws/vpn/vpn.tf
- modules/aws/vpn_instance/vpn-instance.tf
- modules/aws/worker-asg/worker-asg.tf
Now we have installation tag but we don't have a distinct tag between CPs and tenants. For tracking purposes it is worthy
> Add a common tag to CP resources for tracking purposes

- templates/files/conf/k8s-addons
Towards https://github.com/giantswarm/giantswarm/issues/11236
For now kubectl wait hangs at some point due to timeout accessing API and never retries again. That's why it fails eventually
> Check calico with retries

- CHANGELOG.md
- modules/azure/vault/variables.tf
- modules/azure/vault/vault.tf
- platforms/azure/giantnetes/main.tf
- platforms/azure/giantnetes/variables.tf
This PR aims at restoring the functionality of the conveyor pipelines on azure.
Currently the conveyor job assumes that we are using `flatcar linux` in all virtual machines in an azure installation.
This is not true, as most installations still have coreOS in their vault instance.
This PR adds 2 new variables and the `plan` section of the vault VM resource is now dynamic based on the actual image used.
The default behaviour is to use flatcar (in new installations) and can be overridden by setting appropriate variable values overrides in the `installations` repo.
> Avoid setting plan for azure vault instances still running coreOS

- templates/files/k8s-resource/aws-cni.yaml
To allow our tenant cluster Prometheus to be able to scrape tenant clusters, we need to set the AWS_VPC_K8S_CNI_EXTERNALSNAT to false as otherwise as the POD CIDR of the tenant cluster prometheus server would not be allowed to talk with the tenant cluster. 
This was solved using hostNetwork: true for g8s-prometheus but this property is unusable with the prometheus operator as per https://github.com/prometheus-operator/prometheus-operator/issues/2630
> Allow scraping of TCs for TC prometheus

- docs/installation-guide-azure.md
Towards https://github.com/giantswarm/giantswarm/issues/10361
This PR adds a note in the azure installation documentation to enable versioning in the storage account used to store terraform state.
Note: this is impossible to do via the API, the portal is the only choice.
> Add note about enabling versioning for terraform storage account

- CHANGELOG.md
- templates/master.yaml.tmpl
~~This is a somewhat controversial change:~~
~~Instead of pulling the image on every restart of the unit, we rely on `docker run` to pull it once and then use the local image.~~
~~Pro: We pull less often and it hopefully makes us a bit more tolerant to slow / flaky network,~~
~~Con: We have to use properly tagged images and ensure the correct image is actually on the machine.~~
Decided to make all docker pulls  not fail the unit itself.
Towards https://github.com/giantswarm/giantswarm/issues/12928
> Make docker pull optional before run

- CHANGELOG.md
- modules/azure/master-as/variables.tf
This PR changes the etcd disk size for azure CPs to 64GBs.
On azure, the IOPS for disks are based on the disk size, and 64 is the smallest size we can use to have access to the following level of IOPS (240, currently 120).
This is important because we're hitting the IOPS limit and this is causing the master nodes to crash.
> Change etcd disk size to 64gb

- CHANGELOG.md
- templates/files/k8s-resource/calico-policy-only.yaml
calico-policy-only.yaml deployment needs to be updated to apps/v1
PM: https://github.com/giantswarm/giantswarm/issues/14006
> Updating calico policy only deployment to apps/v1

- CHANGELOG.md
- templates/files/k8s-resource/ingress-controller-cm.yaml
When you hit a non-existing endpoint on CP, the default backend is adding their server token in the headers and on the default HTML.
This is recognized as a security issue.
Adding server-tokens: "false" will remove it. IT's already in place in TC
> add server-tokens: "false" to IC config

- CHANGELOG.md
- platforms/azure/giantnetes/variables.tf
Towards: https://github.com/giantswarm/giantswarm/issues/13978
We decided to increate VM size for master nodes on azure because sometimes they can't keep the pace with the requested load.
> Changed default VM size for azure master nodes to Standard_D4s_v3

- modules/azure/blob/blob.tf
- modules/azure/master-as/master-ignition.tf
- modules/azure/vnet/vnet-subnets.tf
- platforms/azure/giantnetes/main.tf
- platforms/azure/giantnetes/variables.tf
> Update azurerm to latest version 2.39

- modules/aws/master/master-iam.tf
- modules/aws/master/variables.tf
- modules/aws/worker-asg/worker-asg.tf
- modules/aws/worker-asg/worker-iam.tf
- platforms/aws/giantnetes/main.tf
Limit node role to restrict access to the CP worker asg only
> Restrict cluster autoscaler required policy

- CHANGELOG.md
- modules/aws/bastion/bastion.tf
- modules/aws/bastion/variables.tf
- platforms/aws/giantnetes/main.tf
Towards https://github.com/giantswarm/giantswarm/issues/15441
> Allow node-exporter metrics on bastion from pod cidr

- CHANGELOG.md
- templates/files/config/audit-policy.yaml
- templates/files/manifests/api-server.yaml
Enables auditing for use during the sysdig evaluation.
DynamicAuditing is deprecated as of k8s 1.19, so this will need to be reverted eventually. Sysdig will provide an alternative mechanism.
Additional discussion on Slack https://gigantic.slack.com/archives/C3S482Z98/p1612459837031600
> Add DynamicAuditing feature gate and audit config

- CHANGELOG.md
- platforms/azure/giantnetes/variables.tf
- templates/files/conf/azure-master.yaml
- templates/files/conf/azure-worker.yaml
This PR adds support to use azure managed identity to allow kubernetes components to login to azure APIs instead of a service principal.
If either the client ID or the client Secret of the service principal are not set, it will use the managed identity.
Please note this is a PR towards the 3.3 release branch
> Azure Managed Identity optional support

- modules/aws/master/variables.tf
- modules/aws/worker-asg/variables.tf
towards https://github.com/giantswarm/giantswarm/issues/16188
8GB disk has causes warning that we get `Warning: EBS Volumes are out of burst balance`, increasing the disk a little bit should give us better performance, its not critical or urgent but can improve overall speed of AWS CP
the cost increase should be low (around 10$ per month for whole CP)
> aws-increase-root-disk

- examples/vmware/bootstrap.sh
- modules/vmware/bastion/data.tf
- modules/vmware/bastion/main.tf
- modules/vmware/bastion/variables.tf
- modules/vmware/bastion/versions.tf
- modules/vmware/nsx-t/data.tf
- modules/vmware/nsx-t/dhcp.tf
- modules/vmware/nsx-t/dhcp_bastion.tf
- modules/vmware/nsx-t/locals.tf
- modules/vmware/nsx-t/outputs.tf
- modules/vmware/nsx-t/segments.tf
- modules/vmware/nsx-t/variables.tf
- platforms/vmware/giantnetes/main.tf
- platforms/vmware/giantnetes/variables.tf
- platforms/vmware/giantnetes/versions.tf
This PR:
- adds support for a single bastion for an installation. the bastion resides in its own subnet which is attached to the same tier 1 router as the MC subnet so can access MC nodes.
> Create bastions in VMware installations

- modules/aws/vpc/variables.tf
- modules/aws/vpc/vpc-subnet-cni.tf
- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
remove old unused CNI subnets that were left after migration to v2
> remove-aws-cni-v1

- CHANGELOG.md
- templates/files/config/kubelet-master.yaml.tmpl
- templates/files/config/kubelet-worker.yaml.tmpl
This change is already pushed to WCs. 
Flag description:
> kernelMemcgNotification, if set, the kubelet will integrate with the kernel memcg notification to determine if memory eviction thresholds are crossed rather than polling. Dynamic Kubelet Config (beta): If dynamically updating this field, consider that it may impact the way Kubelet interacts with the kernel. Default: false
https://v1-20.docs.kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
> Add kubelet flag to better detect memory eviction threshold

- CHANGELOG.md
- modules/azure/master-as/master-ignition.tf
Towards: https://github.com/giantswarm/giantswarm/issues/19843
180 days is what we have in workload clusters
> Change Azure storage account authentication key (SAS) TTL to 180 days

- modules/aws/bastion/bastion-logs.tf
- modules/aws/bastion/bastion.tf
- modules/aws/bastion/variables.tf
- modules/aws/master/master.tf
- modules/aws/master/variables.tf
- modules/aws/s3/s3.tf
- modules/aws/s3/variables.tf
- modules/aws/vault/variables.tf
- modules/aws/vault/vault-elb.tf
- modules/aws/vault/vault.tf
- modules/aws/vpc/variables.tf
- modules/aws/vpc/vpc.tf
- modules/aws/worker-asg/variables.tf
- modules/aws/worker-asg/worker-asg.tf
- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
towards https://github.com/giantswarm/vodafone/issues/493
add an option to add custom tags to all was resources
tested on ginger, vault is not replaced, most of the resources are only updated in place ( except nodes which are rolled)
> aws-add-additional-tags-variable

- modules/aws/bastion/bastion.tf
- modules/aws/worker-asg/worker-iam.tf
- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
- templates/master.yaml.tmpl
- templates/worker.yaml.tmpl
add service to tag all EBS volumes attached to an AWS instance to ensure all tags have the additional tags
towards https://github.com/giantswarm/vodafone/issues/493
> aws-tag-all-volumes

- CHANGELOG.md
- templates/files/conf/setup-kubelet-environment
Related to https://github.com/giantswarm/giantswarm/issues/20118
The `setup-kubelet-environment` script is never run with any arguments so the previous check for if it's a master node of not would always end up thinking it was a worker node.
This change creates different script content based on the node type at templating stage.
> Correctly calculate max pods for control plane nodes

- templates/files/k8s-resource/aws-cni.yaml
new version of flatcar could cause issue where the table file is missing and it will be mounted as dir and cause errors
> fix-aws-cni-xtables

- CHANGELOG.md
- platforms/azure/giantnetes/main.tf
- platforms/azure/giantnetes/variables.tf
On azure, when running terraform from the SREs machines, we used to rely on the locally set up credentials to interact with azure API.
This proved to be unreliable and ineffective for a couple of reasons:
- lighthouse access that we request to customers for our own access does not have all required permissions
- CI/CD uses a different authentication method, leading to problems
With this PR we force the presence of service principal credentials as variables.
> In azure, force service principal credentials to be explicitely set.

- CHANGELOG.md
- platforms/aws/giantnetes/variables.tf
- templates/files/conf/k8s-addons
- templates/files/k8s-resource/calico-crd-installer-rbac.yaml
- templates/files/k8s-resource/calico-crd-installer.yaml
- templates/files/k8s-resource/calico-policy-only.yaml
- templates/files/k8s-resource/vault-token-reviewer.yaml
- templates/master.yaml.tmpl
First bunch of components updates for AWS:
- Bump policy-only manifests to calico 3.21.3 (currently used by AWS only).
- Bump etcd to 3.4.18.
- Bump k8s to 1.21.9 for AWS
Trying to group them in smaller PR for easier review
> Bump components

- templates/files/k8s-resource/ingress-controller-app.yaml
Its enabled by default and is not required for this setup.
Future versions will have this disabled by default anyway.
> Disable use-forwarded-headers for nginx-ingress-controller-app

- CHANGELOG.md
- platforms/azure/giantnetes/main.tf
- templates/files/conf/azure-cni
routing was broken for pods towards vault host because of a wrong CIDR in the masquerading unit for azure cni
> Fix CIDR in Azure CNI masquerading unit.

- CHANGELOG.md
- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
- platforms/azure/giantnetes/main.tf
- platforms/azure/giantnetes/variables.tf
- templates/files/config/kubelet-master.yaml.tmpl
- templates/files/config/kubelet-worker.yaml.tmpl
`gorilla` has a custom cluster domain (instead of `cluster.local`) but this setting was never really applied. See:
- https://github.com/giantswarm/giantnetes-terraform/blob/v5.10.0/templates/files/config/kubelet-master.yaml.tmpl#L10
- https://github.com/giantswarm/giantnetes-terraform/blob/v5.10.0/templates/files/k8s-resource/coredns-all.yaml#L38
Now that we switched to a managed app for coredns, the setting is actually applied, but kubelets still had the hardcoded values.
This PR makes it possible to specify a custom cluster domain and of course defaults to `cluster.local`
> Allow customizing clusterDomain setting in kubelet.

- CHANGELOG.md
- templates/files/k8s-resource/coredns-app.yaml
we need to set those or installations with non-default service CIDRS will not work (example flamingo)
> Set service CIDR and service IP for Coredns app.

- CHANGELOG.md
- templates/files/k8s-resource/ingress-controller-app.yaml
Needed by viking because they use custom SSL certs that need this feature.
It used to be enabled in old nginx ingress controller, was disabled when we moved to the managed app.
> Bump nginx ingress controller app to 2.9.0 and enable `enable-ssl-chain-completion` flag.

- CHANGELOG.md
- modules/azure/master-as/master-as.tf
- modules/azure/vnet/lb-ingress.tf
- modules/azure/vnet/lb-internal-api.tf
- modules/azure/worker-as/worker-as.tf
- templates/files/conf/attach-etcd-disk
Towards: https://github.com/giantswarm/installations/runs/5234134673?check_suite_focus=true
- Using the new `azurerm_linux_virtual_machine_scale_set` terraform resource in place of the deprecated `azurerm_virtual_machine_scale_set`.
- Enable termination notification on masters to make azure-scheduled-events effective.
> Azure master roll

- CHANGELOG.md
- modules/aws/worker-asg/worker-asg.tf
Towards: https://github.com/giantswarm/giantswarm/issues/20953
this PR splits the worker nodes into different ASGs, in order for cluster-autoscaler to be able to scale the right AZ based on the needed availability zone.
This is the first step, where the old ASG is still present. It has to be removed in a follow up PR in order to avoid downtimes during rollout.
It goes along with this change in the deployment CI https://github.com/giantswarm/installations/pull/1980
currently running in ginger.
> Split worker nodes in different ASGs, each one having a single AZ

- CHANGELOG.md
- templates/files/manifests/api-server.yaml
Towards: https://github.com/giantswarm/vodafone/issues/522
we didn't specify the tls ciphers to be exposed by API server. Default is golang's default and apparently those include vulnerable ciphers.
The list of ciphers is taken from [k8s documentation](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)
> Add `--tls-cipher-suites` flag to api-server manifest to disable vulnerable ciphers.

- CHANGELOG.md
- modules/azure/vnet/lb-public.tf
Needed to fix a rollout error on `icecream`.
> Ignore AZ setting for public API LB on azure to avoid unsolvable conflict

- CHANGELOG.md
- platforms/azure/giantnetes/variables.tf
- templates/files/apps/common/coredns-app.yaml
- templates/files/apps/common/ingress-controller-app.yaml
- [Azure] Bump flatcar to `3139.2.0`.
- [Azure] Bump coredns to `1.9.0`.
- [Azure] Bump nginx-ingress-controller to `2.10.0`.
> Bump versions for azure

- CHANGELOG.md
- templates/files/apps/common/ingress-controller-app.yaml
Partially resolves https://github.com/giantswarm/giantswarm/issues/21596.
> Apps: Bump nginx-ingress-controller-app to v2.11.0.

- CHANGELOG.md
- templates/files/manifests/api-server.yaml
- templates/master.yaml.tmpl
Towards: https://github.com/giantswarm/giantswarm/issues/21994
because of a suspect bug in flatcar and a wrong config on the network on our side, worker nodes can't talk to API server in the same AZ.
this PR changes some network settings and kubelet binding address to avoid the problem until upstream fixes the issue and allows better configurability
> Fix networking issue

- CHANGELOG.md
- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
- platforms/azure/giantnetes/main.tf
- platforms/azure/giantnetes/variables.tf
- templates/files/conf/containerd-config.toml
Towards: https://github.com/giantswarm/giantswarm/issues/22678
Add containerd registry mirror for docker.io to avoid image pull errors
> Add registry mirror setting for containerd.

- CHANGELOG.md
- templates/files/conf/setup-apiserver-environment
Towards: https://github.com/giantswarm/giantswarm/issues/23831
api server's memory limit calculation was wrong.
> Use 'MemTotal' rather than 'MemFree' to get memory limit for api server.

- CHANGELOG.md
- templates/files/apps/common/cilium-app.yaml
- templates/files/conf/setup-apiserver-environment
- templates/files/manifests/k8s-api-server.yaml.tmpl
Due to the memory and cpu limit calculation we introduced for the API server manifest, there is a big difference between memory/cpu limits and requests in the master nodes. That might lead to overallocation of nodes when other pods are scheduled on masters (thinking about prometheus).
this PR adds a calculated value for memory and CPU limit as well so the overallocation should be minimal.
It also bumps cilium to latest release
> Apiserver requests

- CHANGELOG.md
- templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/23524
Same block of code in masters and workers, but a typo made it fail on workers :disappointed:
> fix typo in journald unit fix

- CHANGELOG.md
- platforms/aws/giantnetes/variables.tf
- platforms/azure/giantnetes/variables.tf
- Revert flatcar to 3227.2.1 to prevent filesystem hang bug (see https://github.com/giantswarm/giantswarm/issues/23831).
- Bump kubernetes to 1.24.8.
> bump k8s and flatcar

- CHANGELOG.md
- templates/files/manifests/controller-manager.yaml
- templates/files/manifests/scheduler.yaml
Working on installing the prometheus agent on Vintage MCs, I noticed that the scheduler and controller manager were missing labels set on default service monitors https://github.com/giantswarm/prometheus-meta-operator/pull/1094
This PR fixes that.
At the same time, I noticed that the scheduler healthcheck is actually checking for the life of the controller manager (using port 10257). I'm guessing both scheduler and controller-manager are running in the host network, which allowed this behavior.
This image is a call to port 10257 using kubectl port-forward on the k8s scheduler (see leader_election_status metric at the end)
> Add missing labels for scheduler and controller manager

- CHANGELOG.md
- modules/aws/master/master-iam.tf
- modules/aws/s3/s3.tf
- modules/aws/worker-asg/worker-iam.tf
Enable loki monitoring with an S3 bucket and permission on the node instance profile
Towards https://github.com/giantswarm/roadmap/issues/1849
> Add loki S3 bucket and permission

- CHANGELOG.md
- modules/aws/master/master-iam.tf
- modules/aws/worker-asg/worker-iam.tf
Mimir needs a specific bucket for its `ruler` component. I already created the bucket on `gauss`, just need to add the permissions to the nodes.
> add permissions for mimir-ruler S3 buckets

- modules/aws/master/master-iam.tf
- modules/aws/worker-asg/worker-iam.tf
towards https://github.com/giantswarm/roadmap/issues/2368
We're testing Loki on v19 on a WC and thus need permissions for accessing the bucket created for this purpose.
This change will be reverted once tested.
> add permissions for loki in v19 test bucket

- CHANGELOG.md
- modules/aws/vault/vault.tf
towards: https://github.com/giantswarm/giantswarm/issues/27314
we added a new exporter to the vault VM and need to open the port in order for it to be scrapable
> allow vault etcd exporter port

- CHANGELOG.md
- templates/files/apps/common/ingress-controller-app.yaml
Also remove defaults. `use-forwarded-headers` is `false` by default, `use-proxy-protocol` gets set to `true` by the chart when installed to AWS.
> nginx-ingress-controller: Improve requests and autoscaling.

- CHANGELOG.md
- modules/aws/s3/s3.tf
- templates/bastion.yaml.tmpl
- templates/master.yaml.tmpl
- templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/24992
As seen here https://www.flatcar.org/docs/latest/setup/security/audit/#enabling-auditd it looks like we enabled the auditd rules but not the audit daemon which is actually needed to have audit logs in a file
> Enable auditd

- CHANGELOG.md
- modules/aws/s3/s3.tf
- modules/aws/s3/variables.tf
- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
Towards https://github.com/giantswarm/roadmap/issues/2366
Loki deletes most of its data, but may miss some. And I was not happy that our retention period was not Loki-specific.
Only thing before merging: I forgot how to actually test my branch on a test cluster :sweat_smile:
> Independent data retention variable for Loki S3 buckets

- CHANGELOG.md
- modules/aws/s3/s3.tf
- modules/aws/s3/variables.tf
- modules/aws/worker-asg/worker-iam.tf
- platforms/aws/giantnetes/main.tf
- platforms/aws/giantnetes/variables.tf
This PR adds tempo and mimir bucket on vintage installations. This is needed so we can try out tempo and migrate to mimir in a bit
> Add tempo buckets
