docs/installation-guide-azure.md
1) We are not going to use MSI (own vm identity) in near future as it's
brokne in 1.7 and 1.8 (only 1.9 is OK). So we need to bound permissions
for service principal. Allow operations in cluster resource group only.
2) Add note to upload secure credentials into keepass
3) Clean up service principal if cluster deleted
Related to: https://github.com/giantswarm/azure-terraform/issues/5
=> Docs. Restrict service principal permissions.

docs/installation-guide-azure.md, examples/azure/example-build/backend-cloud-config.tf, platforms/azure/giantnetes-cloud-config/backend.tf
We don't really need any state for cloud-configs generation.
=> Use local state for cloud configs

cloud-config/master.yaml.tmpl
=> Upgrade Calico to 3.0.1

modules/azure/bastion-as/bastion.tf, modules/azure/master-as/master-as.tf, modules/azure/vault/vault.tf, modules/azure/vnet/nic-vault.tf, modules/azure/worker-as/worker-as.tf
Partially fixes: https://github.com/giantswarm/azure-terraform/issues/4
EDIT:
I also added DNS entry for Vault, so Fully fixes https://github.com/giantswarm/azure-terraform/issues/4
=> Use hostnames w/o dashes

cloud-config/master.yaml.tmpl, cloud-config/worker.yaml.tmpl
we already have node exporter managed by g8s-kubernetes
=> Remove node-exporter in favor kubernetes managed one

cloud-config/master.yaml.tmpl
Towards: https://github.com/giantswarm/giantswarm/issues/2135
Requires RBAC changes to be merged for further update
=> Replace kube-dns with coredns

cloud-config/master.yaml.tmpl
=> RBAC & PSP

cloud-config/master.yaml.tmpl
=> Add missing coredns ClusterRole

cloud-config/master.yaml.tmpl, cloud-config/worker.yaml.tmpl, ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl
update k8s to 1.9
update etcd to 3.3.1
update calico to 3.0.2
=> Update k8s, etcd and calico.

ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl
=> Fix kubelet /var/log mount

cloud-config/master.yaml.tmpl, cloud-config/worker.yaml.tmpl, ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl
we found that these two manifests were not applied for a while.
=> Fix typos in manifest naming for azure

modules/azure/vnet/nic-master.tf
this fixes `opsctl ssh gollum master1`
=> Add master DNS entry for ssh

docs/installation-guide-azure.md
=> DOCS: Fix typos in azure guide.

cloud-config/master.yaml.tmpl, cloud-config/worker.yaml.tmpl, ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/2527
=> Disable martians logs

docs/installation-guide-aws.md
Moved from aws-terraform and rephrased.
=> DOCS: Added section about DNS zone.

modules/aws/bastion/bastion.tf, modules/aws/bastion/variables.tf, platforms/aws/giantnetes/main.tf
Use IPsec subnet for ssh access if using VPN.
=> Restrict bastion ssh rule for VPN case.

docs/installation-guide-aws.md, modules/aws/s3/s3.tf, modules/aws/vpc/variables.tf, modules/aws/vpc/vpc.tf, platforms/aws/giantnetes/main.tf
- Enable S3 bucket server-side encryption
- Restrict S3 access from VMs to ignition bucket only
Fixes: https://github.com/giantswarm/giantswarm/issues/2796
=> Enable S3 bucket encryption and restrict S3 access.

cloud-config/master.yaml.tmpl, cloud-config/worker.yaml.tmpl, ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl
part of https://github.com/giantswarm/giantswarm/issues/2642
=> Move node token to /etc/tokens/node

cloud-config/master.yaml.tmpl, cloud-config/worker.yaml.tmpl, ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl
See bug: https://github.com/systemd/systemd/issues/8524
Fixes: https://github.com/giantswarm/giantswarm/issues/2862
=> Workaround for systemd-networkd behavior

docs/installation-guide-azure.md
- replace az cli commands with terraform taints
- add removal of cloud-config terraform files
=> DOCS: Update Azure installation guide

modules/aws/vpc/vpc.tf
fixes: https://github.com/giantswarm/giantswarm/issues/2875
=> Add S3 endpoint policy for aws-operator

cloud-config/master.yaml.tmpl, cloud-config/worker.yaml.tmpl, ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl
Fixes: https://github.com/giantswarm/giantswarm/issues/2861
=> Allow AWS and Azure volumes resizing

cloud-config/master.yaml.tmpl, cloud-config/worker.yaml.tmpl, ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl
1.9.6 has multiple fixes that related to Azure disks (e.g https://github.com/kubernetes/kubernetes/pull/60183)
=> Bump to 1.9.6

docs/installation-guide-aws.md, examples/logging-policy.json, modules/aws/s3/s3.tf
Towards https://github.com/giantswarm/giantswarm/issues/2726
=> Enable S3 access logs for existing buckets

docs/installation-guide-aws.md, examples/lifecycle-configuration.json
Towards https://github.com/giantswarm/giantswarm/issues/2726
=> Add expiration lifecycle for the access logs

.circleci/config.yml, misc/e2e-aws.sh
this also fixes failed CI, because of missing logging bucket.
=> Fix CircleCI workflow for master branch

modules/azure/bastion-as/bastion.tf, modules/azure/dns/dns.tf, modules/azure/master-as/master-as.tf, modules/azure/resource-group/resource-group.tf, modules/azure/vault/vault.tf, modules/azure/vnet/lb-api.tf, modules/azure/vnet/lb-ingress.tf, modules/azure/vnet/lb-vault.tf, modules/azure/vnet/nsg-bastion.tf, modules/azure/vnet/nsg-vault.tf, modules/azure/vnet/nsg-worker.tf, modules/azure/vnet/rt-worker.tf, modules/azure/vnet/vnet-subnets.tf, modules/azure/worker-as/worker-as.tf
`Environment` => `GiantSwarmInstallation`
fixes: https://github.com/giantswarm/giantswarm/issues/2775
=> Switch Azure to new tags

misc/e2e-aws.sh
Detect changes in all commits of pull request, not only of the last commit.
I also disabled all except "squashing" for master branch. So for master branch we have to check only last commit (1 PR == 1 commit).
=> Properly detect changes

.circleci/config.yml, misc/e2e-azure.sh
adds CI build script that capable to build cluster and checks for `Ready` nodes.
conformance tests coming.
=> Add e2e CI check for Azure

misc/e2e-azure.sh
Enabled e2e conformance tests for Azure too.
=> Enable e2e conformance tests for Azure CI

ignition/users.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/2867
=> Adjust user accounts list for certificate based authorization

ignition/aws/master.yaml.tmpl, ignition/aws/vault.yaml.tmpl, ignition/aws/worker.yaml.tmpl, ignition/azure/master.yaml.tmpl, ignition/azure/vault.yaml.tmpl, ignition/azure/worker.yaml.tmpl, ignition/bastion.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/2867
=> Allign sshd_config with guest cluster version

ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl, ignition/azure/master.yaml.tmpl, ignition/azure/worker.yaml.tmpl
This does not change actual behavior, but just aligns with guest clusters.
https://github.com/giantswarm/k8scloudconfig/pull/359
=> Remove explicit hostname label

.circleci/config.yml, misc/e2e-aws.sh, misc/e2e-azure.sh
Makes conformance tests optional.
This is steps one to relax our experience with CI. Next step is to enable this only for master branch.
=> Disable conformance tests by default.

ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl, ignition/azure/master.yaml.tmpl, ignition/azure/worker.yaml.tmpl
Fixes: https://github.com/giantswarm/giantswarm/issues/2865
=> Bump kubernetes to 1.10.2

ignition/azure/worker.yaml.tmpl
=> fix-proxy-kubeconfig

ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl, ignition/azure/master.yaml.tmpl, ignition/azure/worker.yaml.tmpl, ignition/bastion.yaml.tmpl, misc/e2e-azure.sh
Had a race condition before while trying get ssh CA while vault address being unresolvable
=> Add wait for domains

docs/installation-guide-azure.md, modules/azure/bastion-as/bastion.tf, modules/azure/bastion-as/variables.tf, modules/azure/master-as/master-as.tf, modules/azure/master-as/variables.tf, modules/azure/worker-as/variables.tf, modules/azure/worker-as/worker-as.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf
- docs changes
- add configurable failure domains (German cloud has 2 failure domains in central region, by default 3)
=> Changes necessary for Azure German Cloud

ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl, ignition/azure/master.yaml.tmpl, ignition/azure/worker.yaml.tmpl, ignition/bastion.yaml.tmpl
https://github.com/giantswarm/giantswarm/issues/3176
=> Switch requesting SSH ca public key to curl instead of vault client

docs/installation-guide-aws.md, docs/installation-guide-azure.md
Following https://github.com/giantswarm/installations/pull/309
=> Update docs with states in installations repo

misc/e2e-azure.sh, modules/azure/worker-as/variables.tf, modules/azure/worker-as/worker-as.tf
Towards https://github.com/giantswarm/giantswarm/issues/2997
Tested on `gollum`.
=> Keep data disks on worker destroy

ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl, modules/aws/master/master.tf, modules/aws/master/variables.tf, modules/aws/worker-asg/variables.tf, modules/aws/worker-asg/worker-asg.tf, platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf
Towards: https://github.com/giantswarm/adidas/issues/306
I didn't tested this yet, but want to know your thoughts on this. 
For China we will need m4 instance type, so I'm making all related stuff configurable
=> Make instance options configurable

ignition/aws/master.yaml.tmpl, ignition/azure/master.yaml.tmpl
towards giantswarm/adidas#320 goes with https://github.com/giantswarm/retagger/pull/83
I included images that were on quay but not retagged in our org
=> switch all images to retagged ones in our quay org

ignition/aws/master.yaml.tmpl, ignition/azure/master.yaml.tmpl
Task: https://github.com/giantswarm/giantswarm/issues/2644
cert-manager (managed by draughtsman) replaced kube-lego.
=> remove kube-lego

platforms/aws/giantnetes/variables.tf
Scaled down one worker in `ginger` w/o  issues. So let's scale down AWS by default  too.
=> Have 3 workers in AWS

ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl, ignition/azure/master.yaml.tmpl, ignition/azure/worker.yaml.tmpl
towards https://github.com/giantswarm/giantswarm/issues/3253
Adding calico-certs as a requirement for k8s-kubelet
=> add calico certs as a requirement for kubelet

ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl, ignition/azure/master.yaml.tmpl, ignition/azure/worker.yaml.tmpl
to align with guest cluster https://github.com/giantswarm/k8scloudconfig/pull/390
=> add add-eviction-policies

ignition/aws/master.yaml.tmpl, ignition/azure/master.yaml.tmpl, misc/e2e-aws.sh
Towards https://github.com/giantswarm/giantswarm/issues/3300
=> Add retry logic into certs units

ignition/aws/master.yaml.tmpl, ignition/aws/worker.yaml.tmpl, ignition/azure/master.yaml.tmpl, ignition/azure/worker.yaml.tmpl
Fixes https://github.com/giantswarm/giantswarm/issues/3475
=> Wipe docker disk

ignition/aws/master.yaml.tmpl, ignition/azure/master.yaml.tmpl
enable metrics scraping for IC controller 
towards  https://github.com/giantswarm/giantswarm/issues/3537
=> enable-monitoring-for-IC

docs/installation-guide-azure.md, examples/azure/example-build/envs.sh, modules/azure/dns/dns.tf, modules/azure/vnet/nic-bastion.tf, modules/azure/vnet/outputs.tf, modules/azure/vnet/variables.tf, modules/azure/vnet/vnet-subnets.tf, modules/azure/vpn/variables.tf, modules/azure/vpn/vpn.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf
- Create VPN gateway and other required resources
- Manage shared key externally (users creates VPN connection resource with shared key on it's own)
=> Add VPN support

ignition/aws/master.yaml.tmpl
short term cure for https://github.com/giantswarm/giantswarm/issues/3582
=> Don't wipe docker for master AWS

modules/aws/master/master-elb.tf, modules/aws/vault/vault-elb.tf
Towards https://github.com/giantswarm/giantswarm/issues/3543
=> Allow host and guest node cidrs for internal elb access

ignition/azure/master.yaml.tmpl
Looks like in Azure disk also flipping. This is just a mitigation.
Mitigate: https://github.com/giantswarm/giantswarm/issues/3700
=> Mitigate issue with Azure disk flip

ignition/bastion-users.yaml
add conveyor user to bastions
towards https://github.com/giantswarm/giantswarm/issues/3806
=> add conveyor ssh user

misc/e2e-aws.sh, misc/e2e-azure.sh, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/3617
=> Add kernel modules required for IPVS

misc/e2e-azure.sh, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Part of: https://github.com/giantswarm/giantswarm/issues/3922
=> Upgrade calico to 3.2.0

misc/e2e-aws.sh, misc/e2e-azure.sh, templates/master.yaml.tmpl
Towards: https://github.com/giantswarm/giantnetes-terraform/issues/132
The example  ishere: https://circleci.com/gh/giantswarm/giantnetes-terraform/1424
=> Failed units status in CI

README.md
Towards: https://github.com/giantswarm/giantswarm/issues/3991
=> Change terminology from host cluster to control plane

misc/e2e-azure.sh, templates/bastion.yaml.tmpl
As we anyway keep user accounts on bastions, we can remove sso ssh from those nodes
=> Remove sso from bastions

modules/aws/vault/vault.tf, modules/azure/vnet/nsg-vault.tf
Part of: https://github.com/giantswarm/giantswarm/issues/3986
Allow scrape cert-exporter
=> Open cert-exporter port on Vault node

README.md, docs/installation-guide-aws.md
add info how install terraform plugins
=> add info about isntalling plugins

templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/3617
Second stage
=> Enable ipvs proxymode in kube-proxy

templates/master.yaml.tmpl
I managed to make a mistake in one-line change :D
=> Fix the ipvs flag in kube-proxy

modules/aws/dns/dns.tf
add some data to aws route53 zone comment to found out when it was created for CI cleaner
for https://github.com/giantswarm/ci-cleaner/pull/21
=> add json date of last update to route53 zone for CI cleaner

modules/aws/vault/vault.tf, templates/master.yaml.tmpl
let's be good boiiis and bump calico
=> bump calico to 3.2.3

templates/master.yaml.tmpl, templates/vault.yaml.tmpl, templates/worker.yaml.tmpl
1. Ask before reboot/shutdown
2. Modify PS1 with additional info 
towards: https://github.com/giantswarm/giantswarm/issues/4407
=> Warning for control-plane nodes

modules/aws/vault/vault.tf, modules/aws/vpc/vpc.tf
- seems the only way to fix count issue 100% is to hardcode, see upstream issue (proper fix in 0.12).
- see comment why we need to disable s3 vpc endpoint Part of https://github.com/giantswarm/giantswarm/issues/4406
=> Fix count issue and disable S3 vpc endpoint for us-east-1

misc/e2e-aws.sh, misc/e2e-azure.sh
we already do that in Dockerfile https://github.com/giantswarm/docker-terraform-and-stuff/blob/master/Dockerfile#L28
=> remove ansible installation

templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Part of: https://github.com/giantswarm/giantswarm/issues/2070
=> Bump certctl version

misc/e2e-aws.sh, templates/vault.yaml.tmpl
we somehow forget to add this settings for vault node
=> limit-logs-vault

templates/master.yaml.tmpl, templates/worker.yaml.tmpl
I also moved kubeconfigs into separate folder to not mess up the things with mounting separate files into same folder
=> Use kube-proxy config from configmap

misc/e2e-azure.sh, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
towards https://github.com/giantswarm/giantswarm/issues/4521
details about the race issue are here: https://github.com/giantswarm/giantswarm/issues/4521#issuecomment-441014433
=> fix-azure-network race issue

templates/master.yaml.tmpl, templates/worker.yaml.tmpl
integrating 1.12 k8scc changes into control plane
almost similar changes like for KVM
=> changes to 1.12

misc/e2e-azure.sh, templates/master.yaml.tmpl
=> fix fix-azure-kube-proxy

templates/worker.yaml.tmpl
Related to this PM
giantswarm/giantswarm#4777
This PR double the inotify watches
Signed-off-by: Julien Garcia Gonzalez <julien@giantswarm.io>
=> double fs.inotify.max_user_watches

templates/master.yaml.tmpl
we  somehow forgot to add audit-policy file so no logs were collected
for https://github.com/giantswarm/giantswarm/issues/4830
=> enable audit logs

misc/e2e-aws.sh, misc/e2e-azure.sh, templates/master.yaml.tmpl
related: https://github.com/giantswarm/giantswarm/issues/2984
=> Disable insecure port and anon auth

templates/master.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/5232
=> Upgrade IC version to 0.21 to avoid race condition

templates/master.yaml.tmpl, templates/worker.yaml.tmpl
apply the fix from this pr https://github.com/giantswarm/hive/pull/416 to terraform
=> fix-certctl-policy

templates/master.yaml.tmpl
Towards: https://github.com/giantswarm/giantswarm/issues/5222
=> Add feature gate ttlAfterFinished for jobs

modules/aws/vault/outputs.tf, modules/aws/vault/variables.tf, modules/aws/vault/vault-iam.tf, modules/aws/vault/vault-kms-endpoint.tf, modules/aws/vault/vault-kms.tf, modules/aws/vault/vault.tf, platforms/aws/giantnetes/main.tf
Towards https://github.com/giantswarm/giantswarm/issues/5436
=> KMS setup for vault auto-unseal in AWS

platforms/aws/giantnetes/variables.tf, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
remove CoreOS alpha channel and upgrade k8s with CVE fix
=> update cores and hyperkube

docs/installation-guide-azure.md, modules/azure/vault/keyvault.tf, modules/azure/vault/variables.tf, modules/azure/vault/vault.tf, platforms/azure/giantnetes/bootstrap.sh, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf
Towards https://github.com/giantswarm/giantswarm/issues/5436
=> Add key vault for auto-unseal

misc/e2e-aws.sh, misc/e2e-azure.sh, modules/aws/vault/variables.tf, modules/azure/vault/keyvault.tf, modules/azure/vault/variables.tf, modules/azure/vault/vault.tf, platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf
Towards https://github.com/giantswarm/giantswarm/issues/5436
=> Setup auto-unseal for supported envs only

docs/installation-guide-aws.md, platforms/aws/giantnetes/main.tf, templates/vault.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/5436
=> Render vault seal block

templates/master.yaml.tmpl
It needs some time before start
=> Fix debug-tools service

modules/azure/vault/vault.tf, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards:https://github.com/giantswarm/giantswarm/issues/5542
=> Get back kube-proxy to iptables mode

.circleci/config.yml, templates/master.yaml.tmpl
will be useful for draining masters in conveyor in order to easily select master1, master2 and master3
=> add-labels-to-masters

templates/master.yaml.tmpl, templates/worker.yaml.tmpl
towards https://github.com/giantswarm/giantswarm/issues/5460
also, adjust settings for CP to be able to pass upstream conformance test
similar to this https://github.com/giantswarm/aws-operator/pull/1434 or tenants
=> use-proper-hostname

templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/5507
=> Remove deprecated sshd option

templates/master.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/5292
Those feature-gates are default starting from 1.12
=> Remove default feature-gates

platforms/azure/giantnetes/main.tf
Towards https://github.com/giantswarm/giantswarm/issues/5684
=> Add vault auto-unseal into azure

templates/master.yaml.tmpl
We need to add this feature gate in order to use ttl for jobs also from the controller
=> Adding TTLAfterFinished feature to k8s controller

docs/installation-guide-aws.md, docs/installation-guide-azure.md, examples/aws/bootstrap.sh
Also updates terraform's tainting syntax as the module path is now specified differently.
=> Minor docs improvements

platforms/aws/giantnetes/main.tf, platforms/azure/giantnetes/main.tf, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
upgrade k8s to 1.14
upgrade calico to 3.6.1
upgrade etcd to 3.13
fix labels for k8s 1.14 https://github.com/giantswarm/giantswarm/issues/5560
=> upgrade-to-1-14

misc/e2e-azure.sh, modules/azure/vault/vault.tf, platforms/aws/giantnetes/main.tf, platforms/azure/giantnetes/main.tf
fixing azure vault , this failed e2e everytime
i accidentally sneaked changed i wanted to do in separate PR with CoreOS owner ID, but don't want to rebuild whole PR again because of the slow e2e tests, sorry :)
=> Upgrade azurerm provider to latest version and fix azure e2e

templates/master.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/4033
=> Label namespaces

templates/master.yaml.tmpl
=> Create giantswarm namespace if it doesn't exist

templates/master.yaml.tmpl
=> Fix labeling loop

templates/master.yaml.tmpl
Bump coredns version in control plane
=> Bump coredns version in control plane

README.md, platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf, templates/master.yaml.tmpl
Signed-off-by: Julien Garcia Gonzalez <julien@giantswarm.io>
=> add audit webhook logs config

docs/installation-guide-aws.md
This ensures no dangling resources remain.
=> Add further deletion info

platforms/aws/giantnetes/main.tf
=> user owner variable

platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf, templates/master.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/6813
=> Add ingress/rbac for external access

modules/aws/vault/variables.tf, modules/aws/vault/vault.tf, platforms/aws/giantnetes/main.tf
towards https://github.com/giantswarm/giantswarm/issues/6936
seems like some weird hack did not include third worker subnet into the security rule
=> fix-security-group-vault

modules/aws/master/master-elb.tf, modules/azure/vnet/lb-api.tf, templates/master.yaml.tmpl
towards https://github.com/giantswarm/giantswarm/issues/6911
adding k8s api healthz micro service for LB health checks
=> add k8s-api-healthz service

templates/master.yaml.tmpl, templates/worker.yaml.tmpl
update k8s to 1.15 and etcd to 3.4.1
=> update k8s to 1.15

platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf, templates/files/k8s-resource/kube-proxy-ds.yaml, templates/files/manifests/api-server.yaml, templates/files/manifests/controller-manager.yaml, templates/files/manifests/scheduler.yaml, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards: https://github.com/giantswarm/giantswarm/issues/5400
Tested on Godsmack
=> Extract hyperkube version

.circleci/config.yml, platforms/aws/giantnetes/main.tf, platforms/azure/giantnetes/main.tf
terraform: `0.12.10`
aws: `2.32.0`
azure: `1.35.0`
=> Update terraform and providers

platforms/azure/giantnetes/variables.tf
From changelog:
```
Fix aggressive VM calls for Azure VMSS
```
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#changelog-since-v1154
=> Bump azure k8s version to 1.15.5

docs/installation-guide-azure.md
Added more specific instructions about dealing with multiple Azure accounts and the `CloudName` setting.
No issue related.
=> Enhancing documentation for azure

docs/installation-guide-azure.md, examples/azure/bootstrap.sh
Made a few enhancements to the documentation and sample code to make the deployment of an installation a little easier (exp. for newbies)
=> Documentation update

misc/e2e-aws.sh, misc/e2e-azure.sh, templates/bastion.yaml.tmpl, templates/files/conf/k8s-addons, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
towards https://github.com/giantswarm/giantswarm/issues/7435
certctl was still using the quay image even in china
=> Use proper docker registry for CP

docs/installation-guide-aws.md
Getting some more info into the install guide for future reference.
towards giantswarm/giantswarm/issues/9023
=> Extend AWS installation docs

templates/files/manifests/api-server.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8631
=> Add control-plane OIDC

misc/e2e-aws.sh, templates/files/k8s-resource/calico-all.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/7519
Not sure how to test this. Can you please give a hint?
=> Upgraded calico for AWS to 3.10.1

templates/files/conf/k8s-addons, templates/files/k8s-resource/ingress-controller-daemonset.yaml, templates/files/k8s-resource/ingress-controller-svc.yaml, templates/master.yaml.tmpl
This PR fixes a missing file after this other PR https://github.com/giantswarm/giantnetes-terraform/pull/310
=> Added missing k8s yaml

templates/files/conf/k8s-addons
Towards https://github.com/giantswarm/roadmap/issues/104
The namespace used for installation-scoped catalogs
=> Add global namespace

misc/e2e-aws.sh, misc/e2e-azure.sh, modules/aws/master/master-elb.tf, modules/aws/master/master.tf, modules/aws/master/variables.tf, platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf, templates/master.yaml.tmpl
Towards https://github.com/giantswarm/roadmap/issues/128
The customer wants to access control-plane k8s API via internal elb
=> Add internal g8s elb

misc/e2e-aws.sh, misc/e2e-azure.sh, modules/aws/master/master-elb.tf, modules/aws/master/master.tf, modules/aws/master/variables.tf, platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf, templates/master.yaml.tmpl
Reverts giantswarm/giantnetes-terraform#319
unfortunately it doesn't work with installations, where elb subnet is `/28`. Rolling back before fixing subnets first
=> Revert "Add internal g8s elb"

misc/e2e-aws.sh, misc/e2e-azure.sh, modules/aws/master/master-elb.tf, modules/aws/master/master.tf, modules/aws/master/variables.tf, platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf, templates/master.yaml.tmpl
Reverts giantswarm/giantnetes-terraform#320
Installations were patched here. We can proceed with this now https://github.com/giantswarm/giantswarm/issues/10622
=> Revert "Revert "Add internal g8s elb""

templates/files/conf/k8s-addons
Removed namespace creation from doc and added heree
=> Proper namespace creation

modules/azure/vnet/nsg-worker.tf, modules/azure/vnet/variables.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf
Towards https://github.com/giantswarm/giantswarm/issues/10911
=> Use 0.0.0.0/0 when it is the only network allowed

templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/11235
=> templates: add k8s-setup-delete-old-node.service

platforms/aws/giantnetes/variables.tf
Related issue: giantswarm/giantswarm#11899
=> Increase the default instance-type

.github/workflows/zz_generated.create_release.yaml, .github/workflows/zz_generated.create_release_pr.yaml, CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/12215
=> Add release workflow

CHANGELOG.md, templates/master.yaml.tmpl
Bug introduced in https://github.com/giantswarm/giantnetes-terraform/pull/337
=> Fix deployment of the IC

CHANGELOG.md, platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/12215
=> Export release version

templates/bastion.yaml.tmpl
towards giantswarm/giantswarm/issues/9390
tested on gauss/bastion2 - it is reachable from Prom.
=> add node-exporter to bastions

CHANGELOG.md
missed this from my previous PR, gonna merge with a ping.
=> update changelog for bastion monitoring

CHANGELOG.md, templates/files/conf/k8s-addons, templates/files/k8s-resource/vault-token-reviewer.yaml, templates/master.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/11373
=> Create vault-token-reviewer sa/binding

CHANGELOG.md, platforms/aws/giantnetes/variables.tf
Towards https://github.com/giantswarm/giantswarm/issues/12587
=> Set default aws worker count to 4

CHANGELOG.md, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/variables.tf
Towards https://github.com/giantswarm/giantswarm/issues/11747
=> Update flatcar linux version to 2512.2.1

CHANGELOG.md, misc/e2e-aws.sh, misc/e2e-azure.sh, platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf, templates/bastion.yaml.tmpl, templates/master.yaml.tmpl, templates/vault.yaml.tmpl, templates/vpn.yaml.tmpl, templates/worker.yaml.tmpl
Towards: https://github.com/giantswarm/giantswarm/issues/11732
This PR uses GS users' data from the `employees` repository for the azure platform
=> Ext employees

CHANGELOG.md, modules/azure/vnet/lb-internal-api.tf, modules/azure/vnet/nic-master.tf, modules/azure/vnet/variables.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf
Towards https://github.com/giantswarm/giantswarm/issues/11373
Also align with AWS
=> Add Azure internal k8s lb

CHANGELOG.md, templates/files/k8s-resource/aws-cni.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/12700
See: https://github.com/giantswarm/giantnetes-terraform/pull/370
=> Add CHANGELOG entry for #370

CHANGELOG.md, templates/bastion.yaml.tmpl, templates/master.yaml.tmpl, templates/vault.yaml.tmpl, templates/worker.yaml.tmpl
@giantswarm/chapter-sre, is there a way to test it apart from merging it and running conveyor manually?
FYI @giantswarm/team-atlas
=> Add Docker metric endpoint to control planes

CHANGELOG.md, modules/aws/vpc/vpc.tf
Towards giantswarm/giantswarm#12940
=> Tag AWS route tables

CHANGELOG.md, platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf, templates/files/manifests/api-server.yaml
Towards https://github.com/giantswarm/giantswarm/issues/12939
=> Use explicit OIDC issuer url configuration

CHANGELOG.md, modules/azure/vnet/nic-master.tf, modules/azure/vnet/nic-worker.tf, modules/azure/vnet/variables.tf, platforms/azure/giantnetes/main.tf
This PR adds support for accelerated networking on supported VMs on azure
=> Azure accelerated net

examples/azure/bootstrap.sh
Added to the sample bootstrap.sh file the versioning snippet and a few useful variables to customize the installation
=> Improved the bootstrap.sh sample file

CHANGELOG.md, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf, templates/master.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/13894
Kubernetes: 1.18.10
Etcd: 3.4.13
Rolled to all test installations - no issues
=> Kubernetes 1.18.10 / etcd 3.4.13

CHANGELOG.md, templates/bastion.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/14042
=> Reduce number of collectors used in node-exporter on bastions

templates/master.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/14161
=> Fix etcd attach circular dependencies 

CHANGELOG.md, templates/master.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/14161
=> Use aws-attach-etcd-dep 0.1.0 version

CHANGELOG.md, modules/aws/bastion/bastion.tf, modules/aws/bastion/variables.tf, modules/aws/dns/dns.tf, modules/aws/master/master-elb.tf, modules/aws/master/master.tf, modules/aws/master/variables.tf, modules/aws/vault/variables.tf, modules/aws/vault/vault-elb.tf, modules/aws/vault/vault.tf, modules/aws/vpn_instance/variables.tf, modules/aws/vpn_instance/vpn-instance.tf, modules/aws/worker-asg/variables.tf, modules/aws/worker-asg/worker-elb.tf, platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf
Towards https://github.com/giantswarm/giantswarm/issues/11637
=> Remove optional route53 dependencies

CHANGELOG.md, templates/files/manifests/api-server.yaml
=> Add labels for api-server

CHANGELOG.md, templates/files/k8s-resource/aws-cni.yaml
Towards https://github.com/giantswarm/giantswarm/issues/14615
=> AWS cni 1.7.5

CHANGELOG.md, modules/aws/worker-asg/worker-asg.tf
=> Add cluster-autoscaler tags to aws asg

platforms/azure/giantnetes/main.tf
=> Skip azure provider registration

CHANGELOG.md, modules/aws/master/master-iam.tf, modules/aws/worker-asg/worker-iam.tf, platforms/azure/giantnetes/variables.tf
=> Extend master/worker iam roles with required access for cluster-autoscaler

CHANGELOG.md, modules/aws/worker-asg/worker-asg.tf
=> Double maximum number of workers in AWS ASG

CHANGELOG.md, modules/azure/master-as/master-as.tf, modules/azure/master-as/variables.tf, modules/azure/resource-group/resource-group.tf, modules/azure/worker-as/variables.tf, modules/azure/worker-as/worker-as.tf, platforms/azure/giantnetes/main.tf
=> Enable msi on azure masters/workers

CHANGELOG.md, modules/aws/vault/vault-iam.tf
Towards https://github.com/giantswarm/giantswarm/issues/12862
=> Extend vault node iam role with access, required to access vault via IAM

CHANGELOG.md, platforms/aws/giantnetes/variables.tf, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/12862
=> Retrieve vault token via IAM role access in AWS CPs

templates/files/k8s-resource/default-storage-class.yaml
towards https://github.com/giantswarm/giantswarm/issues/14039
some fo the Management clusters on AWS have this already manually added
=> storage-class-wait-for-first-customer

CHANGELOG.md, modules/azure/vault/variables.tf, modules/azure/vault/vault.tf, platforms/azure/giantnetes/main.tf
Towards https://github.com/giantswarm/giantswarm/issues/12862
=> Configure vault role with read permissions to VM/VMSS

CHANGELOG.md, examples/azure/bootstrap.sh, examples/azure/terraform-secrets.yaml, templates/files/conf/get-vault-token, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/12862
=> Add get vault token service for azure

CHANGELOG.md, templates/bastion.yaml.tmpl, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/15433
Aligning with workload clusters
=> Add first_boot file into ignition templates

CHANGELOG.md, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/variables.tf, templates/files/conf/k8s-extract, templates/files/config/scheduler.yaml, templates/files/k8s-resource/kube-proxy-ds.yaml, templates/files/manifests/api-server.yaml, templates/files/manifests/controller-manager.yaml, templates/files/manifests/scheduler.yaml, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/15681
=> Kubernetes 1.19 & latest Flatcar

CHANGELOG.md, platforms/azure/giantnetes/variables.tf, templates/files/conf/azure-master.yaml, templates/files/conf/azure-worker.yaml
Backport of https://github.com/giantswarm/giantnetes-terraform/pull/458 to master
=> Azure managed identity

docs/installation-guide-azure.md, examples/azure/bootstrap.sh, examples/azure/terraform-secrets.yaml
This PR fixes the documentation about how to deploy a CP on Azure according to my recent experience of reinstalling gremlin
=> Review docs

CHANGELOG.md, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/variables.tf, templates/files/manifests/api-server.yaml, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/16563
=> Kubernetes 1.20.5 + Flatcar 2765.2.2

CHANGELOG.md, templates/files/config/kubelet-master.yaml.tmpl, templates/files/config/kubelet-worker.yaml.tmpl, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/16883
=> Move enable-server flag to config file

CHANGELOG.md, templates/master.yaml.tmpl
Feature is provided by Flatcar nowadays.
=> Removed oem dir mount unit on Azure. 

templates/files/k8s-resource/ingress-controller-deployment.yaml, templates/files/k8s-resource/rbac-roles.yaml
To match the version deployed to on-prem MCs.
Towards: https://github.com/giantswarm/giantswarm/issues/12864
=> Update nginx-IC to 0.29.0

CHANGELOG.md, templates/master.yaml.tmpl, templates/vault.yaml.tmpl, templates/vpn.yaml.tmpl, templates/worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/17459
=> Add PE SSH keys to MC machines

CHANGELOG.md, modules/aws/vpc/vpc.tf
Towards https://github.com/giantswarm/giantswarm/issues/17459
=> Add VGW attachment for CN installations

docs/installation-guide-aws.md
=> Update AZ number in the AWS installation guide

CHANGELOG.md, templates/files/k8s-resource/ingress-controller-cm.yaml
Towards https://github.com/giantswarm/giantswarm/issues/18200
=> Enable ssl chain completion

CHANGELOG.md, templates/files/conf/setup-kubelet-environment
towards https://github.com/giantswarm/giantswarm/issues/18186
file was copied from TC and it looks like we have one less  hostnetwork pod on worker on MC
=> aws-fix-hostnetworkpods-limit-worker

templates/files/k8s-resource/aws-cni.yaml
=> upgrade-aws-cni-to-1-10-1

CHANGELOG.md, platforms/aws/giantnetes/variables.tf, templates/files/k8s-resource/aws-cni.yaml
Bumped flatcar and use nftables for aws cni
=> Bump flatcar to 3033.2.0 (AWS).

CHANGELOG.md, modules/azure/vnet/lb-ingress.tf, modules/azure/vnet/lb-internal-api.tf, modules/azure/vnet/lb-public.tf, modules/azure/vnet/outputs.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf
Since we need to recrete the load balancer as part of having nginx installed as managed app, I took the chance to change the load balancer to be standard instead of basic.
This will require manual work to be done, I'll take care of that.
=> Switch Azure Load Balancer to be Standard rather than Basic.

templates/files/k8s-resource/aws-cni.yaml
=> upgrade aws cni CRD

CHANGELOG.md, modules/azure/worker-as/worker-as.tf, templates/files/conf/k8s-addons, templates/master.yaml.tmpl
removed code that was just needed for migrating
=> Remove migration commands from k8s-addons (was needed to upgrade from < 6 to 6.0.0).

modules/aws/master/master-iam.tf, modules/aws/master/master.tf, modules/aws/master/variables.tf, modules/aws/sqs/outputs.tf, modules/aws/sqs/sqs.tf, modules/aws/sqs/variables.tf, modules/aws/worker-asg/variables.tf, modules/aws/worker-asg/worker-asg.tf, modules/aws/worker-asg/worker-iam.tf, platforms/aws/giantnetes/main.tf, templates/files/conf/k8s-addons, templates/files/k8s-resource/aws-node-termination-handler-app.yaml, templates/master.yaml.tmpl
Towards: https://github.com/giantswarm/roadmap/issues/815
this PR adds the needed things to make nodes drain themselves on termination
=> Aws termination

CHANGELOG.md, platforms/aws/giantnetes/variables.tf
=> bump k8s and flatcar

CHANGELOG.md, modules/azure/bastion-as/bastion.tf, modules/azure/master-as/master-ignition.tf, modules/azure/vnet/lb-ingress.tf, modules/azure/vnet/lb-internal-api.tf, modules/azure/vnet/lb-public.tf, modules/azure/vnet/lb-vault.tf, modules/azure/vnet/nic-bastion.tf, modules/azure/vnet/nic-vault.tf, modules/azure/vnet/nsg-bastion.tf, modules/azure/vnet/nsg-vault.tf, modules/azure/vnet/nsg-worker.tf, modules/azure/vnet/outputs.tf, platforms/azure/giantnetes/versions.tf
Towards: https://github.com/giantswarm/roadmap/issues/966
We need to bump to latest version of azurerm terraform provider, but that requires a few changes here and there
=> Bump azurerm provider to 3.0.2.

CHANGELOG.md, modules/azure/bastion-as/bastion.tf, modules/azure/bastion-as/variables.tf, modules/azure/blob/blob.tf, modules/azure/dns/dns.tf, modules/azure/master-as/master-as.tf, modules/azure/master-as/variables.tf, modules/azure/resource-group/resource-group.tf, modules/azure/resource-group/variables.tf, modules/azure/vault/variables.tf, modules/azure/vault/vault.tf, modules/azure/vnet/lb-ingress.tf, modules/azure/vnet/lb-internal-api.tf, modules/azure/vnet/lb-public.tf, modules/azure/vnet/lb-vault.tf, modules/azure/vnet/nic-bastion.tf, modules/azure/vnet/nic-vault.tf, modules/azure/vnet/nsg-bastion.tf, modules/azure/vnet/nsg-vault.tf, modules/azure/vnet/nsg-worker.tf, modules/azure/vnet/rt-worker.tf, modules/azure/vnet/variables.tf, modules/azure/vnet/vnet-subnets.tf, modules/azure/vpn/variables.tf, modules/azure/vpn/vpn.tf, modules/azure/worker-as/variables.tf, modules/azure/worker-as/worker-as.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf
This PR allows setting custom tags for all resources.
It's needed by ista and talanx so far
=> Allow setting custom tags to all resources in Azure.

templates/files/config/kubelet-master.yaml.tmpl, templates/files/config/kubelet-worker.yaml.tmpl, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Move kubelet feature flags from systemd unit to config file
=> Azure cloud controller - kubelet feature flags

CHANGELOG.md, modules/aws/master/master-iam.tf
Towards: https://github.com/giantswarm/giantswarm/issues/21840
=> Add `logs:*` permission to masters' IAM role to allow running fluentbit on masters

CHANGELOG.md, templates/files/config/kubelet-master.yaml.tmpl, templates/files/config/kubelet-worker.yaml.tmpl, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Towards: https://github.com/giantswarm/roadmap/issues/1090
=> Cgroup driver

CHANGELOG.md, templates/files/apps/aws/aws-ebs-csi-driver-app.yaml, templates/files/conf/k8s-addons, templates/files/k8s-resource/priority_classes.yaml, templates/master.yaml.tmpl
=> bump some stuff

CHANGELOG.md, templates/files/apps/aws/aws-cloud-controller-manager-app.yaml, templates/files/apps/azure/azure-cloud-controller-manager.yaml, templates/files/apps/common/cilium-app.yaml, templates/files/conf/k8s-addons, templates/files/manifests/controller-manager.yaml
Changes to node setings to align setup with WCs as much as possible
=> Align with WCs

CHANGELOG.md, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/variables.tf, templates/files/apps/aws/aws-cloud-controller-manager-app.yaml, templates/files/apps/aws/aws-ebs-csi-driver-app.yaml, templates/files/apps/azure/azure-cloud-controller-manager.yaml, templates/files/apps/azure/azure-cloud-node-manager.yaml, templates/files/apps/azure/azure-scheduled-events.yaml, templates/files/apps/azure/azuredisk-csi-driver.yaml, templates/files/apps/common/cilium-app.yaml, templates/files/apps/common/coredns-app.yaml, templates/files/apps/common/ingress-controller-app.yaml, templates/files/config/scheduler.yaml, templates/files/manifests/controller-manager.yaml, templates/files/manifests/scheduler.yaml, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
Bump MCs to k8s 1.23 and upgrade all needed components
=> Bump to 1.23

CHANGELOG.md, modules/aws/bastion/variables.tf, modules/aws/master/variables.tf, modules/aws/vault/variables.tf, modules/aws/worker-asg/variables.tf
Towards: https://github.com/giantswarm/egger/issues/45
=> Switch AWS volume types from gp2 to gp3.

CHANGELOG.md, platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/variables.tf, templates/files/apps/aws/aws-cloud-controller-manager-app.yaml, templates/files/apps/aws/aws-node-termination-handler-app.yaml, templates/files/apps/azure/azure-cloud-controller-manager.yaml, templates/files/apps/azure/azure-cloud-node-manager.yaml, templates/files/apps/azure/azure-scheduled-events.yaml, templates/files/apps/common/ingress-controller-app.yaml, templates/files/config/audit-policy.yaml, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
all changes needed to run k8s 1.24
=> support for K8s 1.24

CHANGELOG.md, docs/installation-guide-azure.md, modules/azure/vnet/lb-vault.tf, modules/azure/vnet/vnet-subnets.tf, modules/azure/vpn/variables.tf, modules/azure/vpn/vpn.tf, platforms/azure/giantnetes/main.tf, platforms/azure/giantnetes/variables.tf
We need to get rid of `Basic` LB and public IPs because they're going away on azure.
This PR does just that
Also we use terraform to create the VPN connection entries rather than relying on a manual procedure at MC creation time
=> Azure SKU standard

modules/aws/vpc/vpc.tf
Towards https://github.com/giantswarm/giantswarm/issues/23045#issuecomment-1262244695
This PR allows customers and us to send data to buckets containing `-giantswarm-`.
cc @paurosello what do you think about this?
=> Allow bucket access for auditing

CHANGELOG.md, templates/files/apps/aws/aws-ebs-csi-driver-app.yaml
https://gigantic.slack.com/archives/C01F7T2MNRL/p1665584787473549
=> Update aws-ebs-csi-driver-app.yaml to run EBS controller on masters

CHANGELOG.md, templates/files/apps/common/cilium-app.yaml
Towards https://github.com/giantswarm/roadmap/issues/1510
=> bump cilium to 0.4.0

CHANGELOG.md, templates/files/conf/journald-override.conf, templates/files/conf/journald-storage.conf, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
towards: https://github.com/giantswarm/giantswarm/issues/23524#issuecomment-1285574139
needed  to overcome race condition between auditd and falco that made journald to crash.
=> Apply override to journald systemd unit

CHANGELOG.md, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/variables.tf, templates/files/apps/azure/azuredisk-csi-driver.yaml, templates/files/apps/common/ingress-controller-app.yaml, templates/master.yaml.tmpl
Towards: https://github.com/giantswarm/roadmap/issues/1550
=> bump stuff

CHANGELOG.md, modules/aws/master/master-iam.tf
Towards: https://github.com/giantswarm/giantswarm/issues/24307
=> [AWS] Fix IAM permission for master nodes when using cross-account KMS

CHANGELOG.md, templates/files/manifests/controller-manager.yaml, templates/files/manifests/scheduler.yaml
Towards https://github.com/giantswarm/giantswarm/issues/24059
=> Fix k8s core component scraping

CHANGELOG.md, platforms/aws/giantnetes/variables.tf, platforms/azure/giantnetes/variables.tf, templates/files/apps/aws/aws-ebs-csi-driver-app.yaml, templates/files/apps/azure/azure-cloud-controller-manager.yaml, templates/files/apps/azure/azure-cloud-node-manager.yaml, templates/files/apps/azure/azuredisk-csi-driver.yaml, templates/files/apps/common/cilium-app.yaml, templates/files/apps/common/coredns-app.yaml, templates/files/apps/common/ingress-controller-app.yaml, templates/files/conf/docker-daemon.json, templates/files/conf/setup-apiserver-environment, templates/master.yaml.tmpl, templates/worker.yaml.tmpl
- bump to latest components
- add docker registry mirror setting
=> Bump + registry mirror

CHANGELOG.md, modules/aws/master/master-iam.tf, templates/files/conf/master-instance-healthcheck, templates/files/manifests/k8s-api-server.yaml.tmpl, templates/master.yaml.tmpl
use same script from WCs to check if a master node is healthy or automatically replace it
=> Aws master health

CHANGELOG.md, templates/files/apps/common/cilium-app.yaml
enable hubble UI access through ingress with oauth2 proxy authentication
=> Hubble ingress

CHANGELOG.md, templates/files/apps/common/ingress-controller-app.yaml
Towards https://github.com/giantswarm/adidas/issues/1133.
=> nginx-ingress-controller: Enable `controller.allowSnippetAnnotations`.

CHANGELOG.md, platforms/aws/giantnetes/main.tf, platforms/aws/giantnetes/variables.tf
towards: https://github.com/giantswarm/giantswarm/issues/27102
=> allow customizing vault's etcd disk size.

CHANGELOG.md, templates/files/config/kubelet-master.yaml.tmpl, templates/files/config/kubelet-worker.yaml.tmpl, templates/files/manifests/controller-manager.yaml, templates/files/manifests/k8s-api-server.yaml.tmpl, templates/files/manifests/scheduler.yaml
Issue: https://github.com/giantswarm/roadmap/issues/2536
For reference: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/
=> Remove CSIMigration flags

CHANGELOG.md, modules/aws/vpc/vpc.tf
towards: https://github.com/giantswarm/giantswarm/issues/27358
=> Fix vpce policy to make etcd backups exporter work on vault VMs.

CHANGELOG.md, modules/aws/s3/s3.tf
Towards https://github.com/giantswarm/giantswarm/issues/29092
=> S3 buckets - encryption in transit

CHANGELOG.md, templates/files/apps/common/coredns-app.yaml
Signed-off-by: Matias Charriere <matias@giantswarm.io>
Needed for https://github.com/giantswarm/giantswarm/issues/29345
=> bump coredns-app to 1.21.0
